# Generated by Django 6.1.2 on 2026-10-06 20:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='church_status',
            field=models.CharField(choices=[('SIMPLE_FIDELE', 'Simple fidèle'), ('ASPIRANT', 'Aspirant'), ('DIACRE', 'Diacre'), ('ENUQUE', 'Énuque'), ('PASTEUR', 'Pasteur'), ('INSTRUMENTISTE', 'Instrumentiste'), ('CHORISTE', 'Choriste'), ('MONITEUR/TRICE', 'Moniteur/trice'), ('EVANGELISTE', 'Évangéliste')], default='SIMPLE_FIDELE', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='system_role',
            field=models.CharField(choices=[('MEMBER', 'Membre'), ('PASTOR_ADMIN', 'Administrateur pasteur'), ('DEVELOPER', 'Développeur'), ('SUPER_ADMIN', 'Super administrateur')], default='MEMBER', max_length=30),
        ),
    ]
