# Generated by Django 6.1.2 on 2026-10-06 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('TEXT', 'Texte'), ('AUDIO', 'Audio'), ('VIDEO', 'Vidéo')], default='TEXT', max_length=20)),
                ('audio', models.FileField(blank=True, null=True, upload_to='testimonies/audio/')),
                ('video', models.FileField(blank=True, null=True, upload_to='testimonies/video/')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonies', to=settings.AUTH_USER_MODEL)),
                ('chapel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonies', to='chapels.chapel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestimonyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimony_comments', to=settings.AUTH_USER_MODEL)),
                ('testimony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='testimonies.testimony')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
