# Generated by Django 6.1.2 on 2026-10-06 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvangelizationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('event_type', models.CharField(choices=[('CRUSADE', 'Croisade'), ('EVANGELIZATION', 'Évangélisation'), ('PROGRAM', 'Programme'), ('OUTREACH', 'Mission')], max_length=30)),
                ('description', models.TextField()),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='evangelization/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evangelization_events', to='chapels.chapel')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
