# Generated by Django 6.1.2 on 2026-10-06 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='conventions/covers/')),
                ('is_published', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Choir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choirs', to='chapels.chapel')),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choirs', to='conventions.convention')),
            ],
        ),
        migrations.CreateModel(
            name='ChoirGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='conventions/choirs/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='conventions.choir')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChoirSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lyrics', models.TextField(blank=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='conventions/choirs/audio/')),
                ('video', models.FileField(blank=True, null=True, upload_to='conventions/choirs/video/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='conventions.choir')),
            ],
        ),
        migrations.CreateModel(
            name='ConventionTestimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='conventions/testimonies/audio/')),
                ('video', models.FileField(blank=True, null=True, upload_to='conventions/testimonies/video/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to='conventions.convention')),
            ],
        ),
        migrations.CreateModel(
            name='ConventionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='conventions.convention')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convention_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('convention', 'member')},
            },
        ),
    ]
