# Generated by Django 6.1.2 on 2026-10-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='program',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conventionregistration',
            name='attendees',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='conventionregistration',
            name='chapel_name',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
